### ISSUE TITLE
可否出一个具体flutter应用的demo

### ISSUE THREAD

**Issue by zynzszyn521** [scofield-hello/flutter_arcface_plugin#4]
本人flutter新手一枚，原生的正在了解但是不熟练。所以一般都用flutter package轮子，还请作者帮忙把demo完善下，最好有激活后怎么调用相机来获取照片，然后怎么比对的例子，万分感谢

**Comment by scofield-hello** [comment]
看 arcsoft_sdk_v3分支里的example/lib/main.dart
